# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


# NHO: great seeds!
Character.destroy_all
House.destroy_all
Region.destroy_all
King.destroy_all

robb = King.create(name: "Robb Stark", image: "robb-stark.jpg", story: "Robb is the eldest child of Lady Catelyn and Lord Eddard Stark. Eddard is the head of House Stark, Lord of Winterfell and Lord Paramount of the North, one of the constituent regions of the Seven Kingdoms.")
joffrey = King.create(name: "Joffrey Baratheon", image: "joffrey-baratheon.jpg", story: "Joffrey is believed to be the oldest son and heir of King Robert Baratheon and Queen Cersei Lannister, both of whom entered into a political marriage alliance after Robert took the throne by force from the Mad King Aerys II Targaryen. In reality, his father is Jaime Lannister, the queen's brother and the Lord Commander of the Kingsguard. He has a younger sister, Myrcella, and a younger brother, Tommen , both whom are also the product of Jaime and Cersei's incest.")
balon = King.create(name: "Balon Greyjoy", image: "balon-greyjoy.jpg", story: "Balon Greyjoy is the head of House Greyjoy and Lord of the Iron Islands. The Iron Islands are one of the constituent regions of the Seven Kingdoms and House Greyjoy is one of the Great Houses of the realm. House Greyjoy rule the region from their seat at Pyke and Balon also holds the title Lord Reaper of Pyke. He is a hard, ambitious and ruthless man.")
daenerys = King.create(name: "Daenerys Targaryen", image: "daenerys-targaryen.jpg", story: "Daenerys is the only daughter and youngest child of King Aerys II Targaryen, the Mad King, and his sister-wife Rhaella. Her father died during the Sack of King's Landing, before she was even born. The usurper Robert Baratheon installed himself as king, having defeated Aerys in the conquest known as Robert's Rebellion. Her pregnant mother and young brother Viserys, fled to the island of Dragonstone, the ancestral home of House Targaryen, to escape Robert.")
stannis = King.create(name: "Stannis Baratheon", image: "stannis-baratheon.jpg", story: "Stannis is the second born son of Steffon Baratheon and Cassana Baratheon, the younger brother of the late King Robert Baratheon and older brother of Renly Baratheon. Steffon was the head of House Baratheon and Lord Paramount of the Stormlands. The Stormlands are one of the constituent regions of the Seven Kingdoms and House Baratheon is one of the Great Houses of the realm. Steffon died when the boys were young and Robert inherited his titles.")

north = Region.create(name: "The North", image: "north.jpg", king: robb, story: "The North is one of the constituent regions of the Seven Kingdoms, and was formerly a sovereign nation known as the Kingdom of the North before the Targaryen conquest.")
vale = Region.create(name: "The Vale", image: "vale.jpg", king: robb, story: "The Vale of Arryn or the Vale is one of the constituent regions of the Seven Kingdoms of Westeros. It was formerly a sovereign nation ruled by the Kings of Mountain and Vale before the War of Conquest. The Mountains of the Moon surround the smaller Vale proper,[2] although the valley's name is often applied to all of the Arryns' realm.")
riverland = Region.create(name: "Riverlands", image: "riverlands.jpg", king: robb, story: "The riverlands[1][2] are a central region of the Seven Kingdoms of Westeros, consisting of the rich, fertile, and populous[3] areas around the three forks of the Trident and the northern Blackwater Rush. At the time of Aegon's Conquest the riverlands and the Iron Islands were ruled by House Hoare, the Kings of the Isles and the Rivers,[4] although native river kings ruled centuries earlier.")
ironisland = Region.create(name: "Iron Islands", image: "ironislands.jpg", king: balon, story: "The Iron Islands form part of the Kingdom of the Iron Islands. It had previously formed one of the nine constituent regions of Westeros. They are a group of seven small rocky islands clustered far off the western coast of the mainland of the continent, in Ironman's Bay. The Iron Islands are ruled from Pyke by House Greyjoy.")
stormlands = Region.create(name: "Storm Lands", image: "stormlands.jpg", king: stannis, story: "The Stormlands is one of the nine constituent regions of the Seven Kingdoms. It is located on the south east coast of the continent of Westeros, on the shores of the Narrow Sea, south of the Crownlands and north of Dorne. The Stormlands are ruled from the castle of Storm's End by House Baratheon. They are so-named for the savage and frequent storms from the Narrow Sea that batter the coast. It was originally a sovereign nation known as the Storm Kingdom, until Aegon the Conqueror united Westeros under his rule.")
dorne = Region.create(name: "Dorne", image: "dorne.jpg", king: joffrey, story: "Dorne is one of the nine constituent regions of the Seven Kingdoms. It is the southernmost part of the continent of Westeros, located thousands of miles from Winterfell and the North, and has a harsh desert climate. The Dornishmen are ethnically distinct from the rest of the Seven Kingdoms, being largely descended from Rhoynar refugees who intermarried with the local population of Andals and First Men roughly a thousand years ago. As a result they have very different customs and traditions compared to the other regions of Westeros.")
crownlands = Region.create(name: "Crown Lands", image: "crownlands.jpg", king: daenerys, story: "The crownlands[1][2] is one of the nine constituent regions of the Seven Kingdoms of Westeros. It was never a sovereign nation, instead being contested by river kings, Storm Kings, and local petty kings until Aegon the Conqueror seized control of the area during his War of Conquest and made it his primary foothold on the continent. Since then, the crownlands have been ruled directly by the crown on the Iron Throne, first House Targaryen and, after Robert's Rebellion, House Baratheon. Bastards of noble origin raised in the crownlands are given the surname Waters.")
westerlands = Region.create(name: "Westerlands", image: "westerlands.jpg", king: joffrey, story: "The westerlands[1] is a region in the west of the continent of Westeros.Before the Targaryen conquest, it was known as the Kingdom of the Rock. People from the westerlands are known as westermen.[2][3] The customary surname of noble bastards born in the westerlands is Hill.")

arryn = House.create(name: "Arryn", image: "sigilArryn.jpg", region: vale, story: "House Arryn is one of the Great Houses of Westeros. It has ruled over the Vale of Arryn for millennia, originally as the Kings of Mountain and Vale and more recently as Lords Paramount of the Vale and Wardens of the East under the Targaryen kings and King Robert Baratheon. The nominal head of House Arryn is Robin Arryn, the Lord of the Eyrie, with his mother Lady Lysa acting as Lady Regent until he reaches the age of majority.", motto: "As High as Honor!")
baratheon = House.create(name: "Baratheon", image: "sigilBaratheon.jpg", region: stormlands, story: "House Baratheon of Storm's End was one of the Great Houses of Westeros, although also one of the youngest. It is the current royal house.", motto: "Ours is the Fury!")
greyjoy = House.create(name: "Greyjoy", image: "sigilGreyjoy.jpg", region: ironisland, story: "House Greyjoy is one of the Great Houses of Westeros. It rules over the Iron Islands, a harsh and bleak collection of islands off the west coast of Westeros, from the castle at Pyke. The head of the house is the Lord Reaper of Pyke.", motto: "We do not sow!")
lannister = House.create(name: "Lannister", image: "sigilLannister.jpg", region: westerlands, story: "House Lannister of Casterly Rock is one of the Great Houses of Westeros, one of its richest and most powerful families and oldest dynasties. The major characters Jaime, Cersei, and Tyrion and the recurring characters Tywin, Kevan, and Lancel are members of the house. Tywin is the head of House Lannister and Lord of Casterly Rock.", motto: "Hear me roar!")
stark = House.create(name: "Stark", image: "sigilStark.jpg", region: north, story: "House Stark of Winterfell is an exiled Great House of Westeros, ruling over the vast region known as the North from their seat in Winterfell. It is by far one of the oldest lines of Westerosi nobility, claiming a line of descent stretching back over eight thousand years. The head of the house was the Lord of Winterfell. Before the Targaryen conquest, the leaders of House Stark ruled over the region as the Kings in the North.", motto: "Winter is coming!")
targaryen = House.create(name: "Targaryen", image: "sigilTargaryen.jpg", region: crownlands, story: "House Targaryen is a former Great House of Westeros and was the ruling royal House of the Seven Kingdoms for three centuries, before it was deposed during Robert's Rebellion and House Baratheon replaced it as the new royal House. The few surviving Targaryens fled into exile.", motto: "Fire and Blood!")
tully = House.create(name: "Tully", image: "sigilTully.jpg", region: riverland, story: "House Tully of Riverrun is one of the Great Houses of the Seven Kingdoms. Lord Hoster Tully rules over the riverlands from the Tully seat of Riverrun.  Members of the family tend to have auburn hair, high cheekbones, and bright blue eyes.", motto: "Family, Duty, Honor!")
martell = House.create(name: "Martell", image: "sigilMartell.jpg", region: dorne, story: "House Nymeros Martell of Sunspear is one of the Great Houses of Westeros and is the ruling house of Dorne. 'Nymeros' indicates of the line of Nymeria, but generally it is simply called House Martell. The seat of the Prince of Dorne is Sunspear in southeastern Dorne.", motto: "Unbowed, Unbent, Unbroken!")

eddard = Character.create(name: "Eddard Stark", house: stark, image: "ned-stark.jpg", title: "Lord of Winterfell", story: "Eddard Stark is the head of House Stark and Lord Paramount of the North. The North is one of the constituent regions of the Seven Kingdoms, and House Stark is one of the Great Houses of the realm. House Stark rules the region from their seat of Winterfell, and Eddard also holds the title Lord of Winterfell. In addition, he is the Warden of the North.")
catelyn = Character.create(name: "Catelyn Tully", house: stark, image: "catelyn-stark.jpg", title: "Lady of Winterfell", story: "Catelyn was born into House Tully and is the eldest child of Lord Hoster Tully. She has a younger brother, Edmure, and a younger sister, Lysa. Petyr Baelish was fostered with the Tullys and Catelyn grew up with him. She was betrothed to marry Brandon Stark of Winterfell, but he was brutally murdered by the Mad King, Aerys II Targaryen after Prince Rhaegar had kidnapped Brandon's sister Lyanna. Catelyn instead married Brandon's brother, Eddard. Though they barely knew one another when they wed they have formed a strong and loving marriage.")
snow = Character.create(name: "John Snow", house: stark, image: "jon-snow.jpg", title: "Lord Commander of the Night's Watch", story: "Jon is the bastard son of Lord Eddard Stark of Winterfell, the head of House Stark and Lord Paramount of the North. The North is one of the constituent regions of the Seven Kingdoms in Westeros, and House Stark is one of the Great Houses of the realm. House Stark rules the region from their seat of Winterfell and Eddard also holds the title Lord of Winterfell. He is also the Warden of the North to King Robert Baratheon.")
sansa = Character.create(name: "Sansa Stark", house: stark, image: "sansa-stark.jpg", title: "Princess", story: "Sansa Stark is the second child and eldest daughter of Eddard Stark and Catelyn Stark. She was born and raised in Winterfell, until leaving with her father and sister at the beginning of the series. She has a younger sister Arya Stark, two younger brothers Rickon Stark and Bran Stark, as well as an older brother Robb Stark, and an older illegitimate half-brother, Jon Snow.")
arya = Character.create(name: "Arya Stark", house: stark, image: "arya-stark.jpg", title: "Princess", story: "Arya Stark is the youngest daughter and third child of Lady Catelyn and Lord Eddard Stark. Eddard is the head of House Stark and Lord Paramount of the North. The North is one of the constituent regions of the Seven Kingdoms and House Stark is one of the Great Houses of the realm. House Stark rules the region from their seat of Winterfell and Eddard also holds the title Lord of Winterfell. He is also the Warden of the North to King Robert Baratheon.")
bran = Character.create(name: "Bran Stark", house: stark, image: "bran-stark.jpg", title: "Prince", story: "Bran is the fourth child and second son of Lady Catelyn and Lord Eddard Stark. Eddard is the head of House Stark and Lord Paramount of the North. The North is one of the constituent regions of the Seven Kingdoms and House Stark is one of the Great Houses of the realm. House Stark rules the region from their seat of Winterfell and Eddard also holds the title Lord of Winterfell. He is also the Warden of the North to King Robert Baratheon.")
edmure = Character.create(name: "Edmure Tully", house: tully, image: "edmure-tully.jpg", title: "Lord Paramount of the Trident", story: "Ser Edmure is the son and heir of Lord Hoster Tully. Edmure is the new head of House Tully and thus has recently become the Lord of Riverrun and Lord Paramount of the Riverlands. The Riverlands are one of the constituent regions of the Seven Kingdoms and House Tully is one of the Great Houses of the realm. Riverrun is the ancestral seat of House Tully.")
lysa = Character.create(name: "Lysa Tully", house: arryn, image: "lysa-arryn.jpg", title: "Lady Regent of the Vale", story: "Lysa was born into House Tully and was the second child of Lord Hoster Tully. She had an older sister, Catelyn and a younger brother, Edmure. Petyr Baelish was fostered with the Tullys and Lysa grew up with him.")
renly = Character.create(name: "Renly Baratheon", house: baratheon, image: "renly-baratheon.jpg", title: "Lord of Storm's End", story: "Renly is the third and youngest son of Steffon and Cassana Baratheon. Steffon was the head of House Baratheon and Lord Paramount of the Stormlands. The Stormlands are one of the constituent regions of the Seven Kingdoms and House Baratheon is one of the Great Houses of the realm. Renly has two older brothers Robert and Stannis. Their parents died when the boys were young and Robert inherited his father's titles. Robert led a rebellion against King Aerys II Targaryen, deposing and replacing him as the King on the Iron Throne. He made Renly the Lord of Storm's End following his victory. Renly was only a child during the civil war, so he did not fight.")
theon = Character.create(name: "Theon Greyjoy", house: greyjoy, image: "theon-greyjoy.jpg", title: "Prince of the Iron Islands", story: "Theon is the youngest son of Lord Balon and Lady Alannys Greyjoy. Balon is the head of House Greyjoy and Lord of the Iron Islands. The Iron Islands are one of the constituent regions of the Seven Kingdoms and House Greyjoy is one of the Great Houses of the realm. House Greyjoy rule the region from their seat at Pyke and Balon also holds the title Lord Reaper of Pyke.")
tyrion = Character.create(name: "Tyrion", house: lannister, image: "tyrion-lannister.jpg", title: "Master of Coin", story: "Tyrion Lannister is the youngest son of Joanna Lannister and Lord Tywin Lannister. Tywin is the head of House Lannister, the richest man in the Seven Kingdoms and Lord Paramount of the Westerlands. The Westerlands are one of the constituent regions of the Seven Kingdoms and House Lannister of Casterly Rock is one of the Great Houses of the realm. He is the younger brother of Jaime and Cersei Lannister. His mother Joanna Lannister died giving birth to him. His father and sister hold him in contempt as they blame him for the death.")
cersei = Character.create(name: "Cersei Lannister", house: lannister, image: "cersei-lannister.jpg", title: "Queen Dowager", story: "Cersei is the only daughter and eldest child of Joanna Lannister and Lord Tywin Lannister. Tywin is the head of House Lannister, the richest man in the Seven Kingdoms and Lord Paramount of the Westerlands. The Westerlands are one of the constituent regions of the Seven Kingdoms and House Lannister is one of the Great Houses of the realm. Cersei is the elder twin of Ser Jaime Lannister and the elder sister of Tyrion Lannister. She was raised in privilege in the family seat of Casterly Rock.[2] She is noted for her great beauty.")
jamie = Character.create(name: "Jamie Lannister", house: lannister, image: "jamie-lannister.jpg", title: "Lord Commander of the Kingsguard", story: "Ser Jaime Lannister is a knight of the Kingsguard, a position he has held for twenty years since he was a teenager, the youngest man ever appointed to its membership.[2] He was appointed to the position by the Mad King, Aerys II Targaryen.")
viserys = Character.create(name: "Viserys Targaryen", house: targaryen, image: "viserys-targaryen.jpg", title: "Lord of the Seven Kingdoms", story: "Viserys is the second son and heir of King Aerys II Targaryen, the former ruler of the Seven Kingdoms. During Robert's Rebellion, after Viserys's older brother Rhaegar was killed at the Battle of the Trident, his father sent Viserys and his pregnant mother Queen Rhaella to safety on Dragonstone island. King Aerys was soon afterwards killed during the Sack of King's Landing along with Rhaegar's widow and children, and thus at the age of only five Viserys became the titular head of House Targaryen, though by this point the war was officially lost.")
oberyn = Character.create(name: "Oberyn Martell", house: martell, image: "oberyn-martell.jpg", title: "Prince", story: "Prince Oberyn is the younger brother of Prince Doran Martell and Princess Elia Martell; like most members of House Martell, he is styled Prince instead of Lord. He is nicknamed the Red Viper for his knowledge of poisons and for his unusual, deadly style of combat.")




# NHO: reminder to remove commented out code

# king.regions << region
# region.houses  << house
# house.characters << character

# puts "It succeeded!!!\n\n" if king.save
